version: 0.1

phses:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.favicon
    - styles/main.css
    - images/*
    - dist/bundle.js
